name: PR Build

on:
  pull_request:
    branches: [ main ]
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
# Build Decksteria.Core
  build-core:
    name: Build Decksteria Application
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies for Core Project
        run: dotnet restore "src/Decksteria.Core/Decksteria.Core.csproj"
      - name: Build Core Project
        run: >
          dotnet build "src/Decksteria.Core/Decksteria.Core.csproj"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=true
      - name: Install dependencies for Services Project
        run: dotnet restore "src/Decksteria.Services/Decksteria.Services.csproj"
      - name: Build Services Project
        run: >
          dotnet build "src/Decksteria.Services/Decksteria.Services.csproj"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=true
      - name: Install dependencies for Maui Project
        run: |
          dotnet workload install android
          dotnet workload restore "src/Decksteria.Ui.Maui/Decksteria.Ui.Maui.csproj" --ignore-failed-sources
          dotnet restore "src/Decksteria.Ui.Maui/Decksteria.Ui.Maui.csproj" /p:PublishReadyToRun=true
      - name: Build Maui Project
        run: >
          dotnet build "src/Decksteria.Ui.Maui/Decksteria.Ui.Maui.csproj"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=true
          /p:Platform=x64
      - name: Run tests
        run: >
          dotnet test "src/Decksteria.Base.sln"
          --configuration Release