name: PR Build

on:
  pull_request:
    branches: [ main ]
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
# Build Decksteria.Core
  build-core:
    name: Build Decksteria Application
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies for Maui Project
        run: |
          dotnet workload install android
      - name: Restore Solution
        run: dotnet restore "src/Decksteria.Base.sln"
      - name: Build Solution
        run: >
          dotnet build "src/Decksteria.Base.sln"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=true
          /p:Platform=x64
      - name: Run Tests
        run: >
          dotnet test
          --configuration Release
          --no-build