name: PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
# Build Decksteria.Core
  build-core:
    name: Build Decksteria Application
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies for Core Project
        run: dotnet restore "Decksteria.Core/Decksteria.Core.csproj"
      - name: Build Core Project
        run: >
          dotnet build "Decksteria.Core/Decksteria.Core.csproj"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=true
      - name: Install dependencies for Services Project
        run: dotnet restore "Decksteria.Service/Decksteria.Service.csproj"
      - name: Build Services Project
        run: >
          dotnet build "Decksteria.Service/Decksteria.Service.csproj"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=false
      - name: Install dependencies for Maui Project
        run: |
          dotnet workload restore "Decksteria.Ui.Maui/Decksteria.Ui.Maui.csproj" --ignore-failed-sources
          dotnet restore "Decksteria.Ui.Maui/Decksteria.Ui.Maui.csproj" --runtime win-x64 --framework net8.0-windows10.0.19041.0
      - name: Build Maui Project
        run: >
          dotnet build "Decksteria.Ui.Maui/Decksteria.Ui.Maui.csproj"
          --configuration Release
          --no-restore
          /p:WarningsAsErrors=false
